# Generated by Django 3.2.7 on 2022-06-03 21:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0002_auto_20220603_2111"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="last_migrate_datetime",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="Last migrate date",
            ),
        ),
    ]
