# Generated by Django 3.2.7 on 2022-06-13 10:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0003_transaction_last_migrate_datetime"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Transaction date"
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="system",
            field=models.CharField(max_length=100, verbose_name="System"),
        ),
    ]
