# Generated by Django 3.2.7 on 2022-06-13 10:17

from django.db import migrations


def forwards_func(apps, schema_editor):
    Transaction = apps.get_model("finance", "transaction")

    Transaction.objects.update(system="Visa")


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0004_auto_20220613_1014"),
    ]

    operations = [
        migrations.RunPython(
            forwards_func,
        )
    ]
