# Generated by Django 3.2.7 on 2022-10-11 08:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0010_auto_20221011_0845"),
        ("finance", "0005_auto_20220613_1017"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="transaction",
            options={"verbose_name": "Транзакция", "verbose_name_plural": "Транзакции"},
        ),
        migrations.AlterField(
            model_name="transaction",
            name="amount",
            field=models.FloatField(verbose_name="Сумма"),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="user.client",
                verbose_name="Клиент",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="comment",
            field=models.TextField(blank=True, null=True, verbose_name="Комментарий"),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Дата и время"
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="last_migrate_datetime",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="время последней миграции",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="status",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "In progress"), (2, "Success"), (3, "Canceled")],
                default=1,
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="system",
            field=models.CharField(max_length=100, verbose_name="Платежная система"),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="type",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "refill"), (2, "withdraw")], default=1, verbose_name="Тип"
            ),
        ),
    ]
