# Generated by Django 3.2.7 on 2023-06-18 09:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0006_auto_20221011_0845"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="system",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Платежная система"
            ),
        ),
    ]
