# Generated by Django 3.2.7 on 2024-03-19 12:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0033_auto_20240319_1422'),
        ('finance', '0007_alter_transaction_system'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'verbose_name': 'Транзакція', 'verbose_name_plural': 'Транзакції'},
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.FloatField(verbose_name='Сума'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='user.client', verbose_name='Клієнт'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Коментар'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата та час'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='last_migrate_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='час останньої міграції'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='system',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Платіжна система'),
        ),
    ]
