# Generated by Django 3.2.7 on 2022-06-03 18:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("user", "0002_auto_20220603_1626"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Bet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("result", models.FloatField(verbose_name="Result")),
                ("stake", models.FloatField(verbose_name="Stake")),
                (
                    "type",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "Single")], default=1, verbose_name="Type"
                    ),
                ),
                (
                    "status",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "In progress"), (2, "Success"), (3, "Canceled")],
                        default=1,
                        verbose_name="Status",
                    ),
                ),
                ("on", models.CharField(max_length=50, verbose_name="Bet on")),
                ("rate", models.CharField(max_length=50, verbose_name="Bet rate")),
                ("odds", models.FloatField(verbose_name="Odds")),
                ("commision", models.FloatField(verbose_name="Commision")),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Create date",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bets",
                        to="user.client",
                        verbose_name="Client",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bets",
                        to="bets.event",
                        verbose_name="Event",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bets",
                "verbose_name_plural": "Bets",
            },
        ),
    ]
