# Generated by Django 3.2.7 on 2022-06-03 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("football", "0001_initial"),
        ("bets", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bet",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bets",
                to="football.match",
                verbose_name="Event",
            ),
        ),
    ]
