# Generated by Django 3.2.7 on 2022-06-03 20:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bets", "0002_alter_bet_event"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bet",
            name="commision",
            field=models.FloatField(blank=True, null=True, verbose_name="Commision"),
        ),
        migrations.AlterField(
            model_name="bet",
            name="result",
            field=models.FloatField(blank=True, null=True, verbose_name="Result"),
        ),
    ]
