# Generated by Django 3.2.7 on 2022-06-05 07:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bets", "0003_auto_20220603_2027"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bet",
            name="status",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "In progress"), (2, "Success"), (3, "Lost")],
                default=1,
                verbose_name="Status",
            ),
        ),
    ]
