# Generated by Django 3.2.7 on 2022-06-05 08:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bets", "0004_alter_bet_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bet",
            name="event",
            field=models.TextField(null=True, verbose_name="Event"),
        ),
    ]
