# Generated by Django 3.2.7 on 2022-06-05 08:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bets", "0005_alter_bet_event"),
    ]

    operations = [
        migrations.AddField(
            model_name="bet",
            name="commands",
            field=models.CharField(max_length=1000, null=True, verbose_name="Commands"),
        ),
        migrations.AddField(
            model_name="bet",
            name="country",
            field=models.CharField(max_length=1000, null=True, verbose_name="Country"),
        ),
        migrations.AddField(
            model_name="bet",
            name="date_of_game",
            field=models.CharField(
                max_length=1000, null=True, verbose_name="Date of game"
            ),
        ),
        migrations.AddField(
            model_name="bet",
            name="game_score",
            field=models.CharField(
                max_length=1000, null=True, verbose_name="Game score"
            ),
        ),
        migrations.AddField(
            model_name="bet",
            name="league",
            field=models.CharField(max_length=1000, null=True, verbose_name="League"),
        ),
        migrations.AddField(
            model_name="bet",
            name="number",
            field=models.CharField(
                max_length=1000, null=True, verbose_name="Number of bet"
            ),
        ),
        migrations.AddField(
            model_name="bet",
            name="sport",
            field=models.TextField(max_length=1000, null=True, verbose_name="Sport"),
        ),
        migrations.AlterField(
            model_name="bet",
            name="created_at",
            field=models.CharField(
                max_length=1000, null=True, verbose_name="Create date"
            ),
        ),
        migrations.AlterField(
            model_name="bet",
            name="event",
            field=models.TextField(max_length=1000, null=True, verbose_name="Event"),
        ),
    ]
