# Generated by Django 3.2.7 on 2022-06-05 08:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bets", "0006_auto_20220605_0813"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bet",
            name="commands",
            field=models.CharField(
                default="", max_length=1000, verbose_name="Commands"
            ),
        ),
        migrations.AlterField(
            model_name="bet",
            name="country",
            field=models.CharField(default="", max_length=1000, verbose_name="Country"),
        ),
        migrations.AlterField(
            model_name="bet",
            name="created_at",
            field=models.CharField(
                default="", max_length=1000, verbose_name="Create date"
            ),
        ),
        migrations.AlterField(
            model_name="bet",
            name="date_of_game",
            field=models.CharField(
                default="", max_length=1000, verbose_name="Date of game"
            ),
        ),
        migrations.AlterField(
            model_name="bet",
            name="event",
            field=models.TextField(default="", max_length=1000, verbose_name="Event"),
        ),
        migrations.AlterField(
            model_name="bet",
            name="game_score",
            field=models.CharField(
                default="", max_length=1000, verbose_name="Game score"
            ),
        ),
        migrations.AlterField(
            model_name="bet",
            name="league",
            field=models.CharField(default="", max_length=1000, verbose_name="League"),
        ),
        migrations.AlterField(
            model_name="bet",
            name="number",
            field=models.CharField(
                default="", max_length=1000, verbose_name="Number of bet"
            ),
        ),
        migrations.AlterField(
            model_name="bet",
            name="sport",
            field=models.TextField(default="", max_length=1000, verbose_name="Sport"),
        ),
    ]
