# Generated by Django 3.2.7 on 2022-06-05 08:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bets", "0007_auto_20220605_0817"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bet",
            name="event",
            field=models.CharField(default="", max_length=1000, verbose_name="Event"),
        ),
    ]
