# Generated by Django 3.2.7 on 2022-06-05 09:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bets", "0008_alter_bet_event"),
    ]

    operations = [
        migrations.AddField(
            model_name="bet",
            name="event_id",
            field=models.CharField(default="", max_length=7, verbose_name="Event ID"),
        ),
    ]
