# Generated by Django 3.2.7 on 2022-10-11 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0010_auto_20221011_0845"),
        ("bets", "0009_bet_event_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bet",
            options={"verbose_name": "Ставка", "verbose_name_plural": "Ставки"},
        ),
        migrations.AlterField(
            model_name="bet",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bets",
                to="user.client",
                verbose_name="Килент",
            ),
        ),
        migrations.AlterField(
            model_name="bet",
            name="commands",
            field=models.CharField(default="", max_length=1000, verbose_name="Команды"),
        ),
        migrations.AlterField(
            model_name="bet",
            name="commision",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Комиссия (сумма)"
            ),
        ),
        migrations.AlterField(
            model_name="bet",
            name="country",
            field=models.CharField(default="", max_length=1000, verbose_name="Страна"),
        ),
        migrations.AlterField(
            model_name="bet",
            name="created_at",
            field=models.CharField(
                default="", max_length=1000, verbose_name="Время и дата создания ставки"
            ),
        ),
        migrations.AlterField(
            model_name="bet",
            name="date_of_game",
            field=models.CharField(
                default="", max_length=1000, verbose_name="Время и дата матча"
            ),
        ),
        migrations.AlterField(
            model_name="bet",
            name="event",
            field=models.CharField(
                default="",
                max_length=1000,
                verbose_name="Тип ставки (точный счет, исход и тд)",
            ),
        ),
        migrations.AlterField(
            model_name="bet",
            name="game_score",
            field=models.CharField(
                default="", max_length=1000, verbose_name="Счет игры"
            ),
        ),
        migrations.AlterField(
            model_name="bet",
            name="league",
            field=models.CharField(default="", max_length=1000, verbose_name="Лига"),
        ),
        migrations.AlterField(
            model_name="bet",
            name="number",
            field=models.CharField(
                default="", max_length=1000, verbose_name="Номер ставки"
            ),
        ),
        migrations.AlterField(
            model_name="bet",
            name="odds",
            field=models.FloatField(verbose_name="КЭФ"),
        ),
        migrations.AlterField(
            model_name="bet",
            name="on",
            field=models.CharField(max_length=50, verbose_name="На какой счет ставили"),
        ),
        migrations.AlterField(
            model_name="bet",
            name="result",
            field=models.FloatField(blank=True, null=True, verbose_name="Выигрыш"),
        ),
        migrations.AlterField(
            model_name="bet",
            name="sport",
            field=models.TextField(default="", max_length=1000, verbose_name="Спорт"),
        ),
        migrations.AlterField(
            model_name="bet",
            name="stake",
            field=models.FloatField(verbose_name="Сумма ставки"),
        ),
        migrations.AlterField(
            model_name="bet",
            name="status",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "In progress"), (2, "Success"), (3, "Lost")],
                default=1,
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="bet",
            name="type",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "Single")], default=1, verbose_name="Тип"
            ),
        ),
    ]
