# Generated by Django 3.2.7 on 2022-10-12 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bets", "0010_auto_20221011_0845"),
    ]

    operations = [
        migrations.CreateModel(
            name="Odds",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
            ],
        ),
        migrations.AddField(
            model_name="bet",
            name="odds_value",
            field=models.FloatField(default=0, verbose_name="КЭФ"),
        ),
        migrations.CreateModel(
            name="OddsDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=100,
                        verbose_name="Значение",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                (
                    "odds",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="odds_detail",
                        to="bets.odds",
                        verbose_name="Odds",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="bet",
            name="odds",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bets",
                to="bets.odds",
                verbose_name="Odds",
            ),
        ),
    ]
