# Generated by Django 3.2.7 on 2022-10-12 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("football", "0006_match_kind_of_sport"),
        ("bets", "0011_auto_20221012_1426"),
    ]

    operations = [
        migrations.AddField(
            model_name="odds",
            name="fixture",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="odds",
                to="football.match",
                verbose_name="Событие",
            ),
        ),
    ]
