# Generated by Django 3.2.7 on 2022-10-17 11:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bets", "0012_odds_fixture"),
    ]

    operations = [
        migrations.AddField(
            model_name="odds",
            name="name_en_us",
            field=models.CharField(max_length=255, null=True, verbose_name="Название"),
        ),
        migrations.AddField(
            model_name="odds",
            name="name_es",
            field=models.CharField(max_length=255, null=True, verbose_name="Название"),
        ),
        migrations.AddField(
            model_name="odds",
            name="name_fr",
            field=models.CharField(max_length=255, null=True, verbose_name="Название"),
        ),
        migrations.AddField(
            model_name="oddsdetail",
            name="name_en_us",
            field=models.CharField(max_length=255, null=True, verbose_name="Название"),
        ),
        migrations.AddField(
            model_name="oddsdetail",
            name="name_es",
            field=models.CharField(max_length=255, null=True, verbose_name="Название"),
        ),
        migrations.AddField(
            model_name="oddsdetail",
            name="name_fr",
            field=models.CharField(max_length=255, null=True, verbose_name="Название"),
        ),
    ]
