# Generated by Django 3.2.7 on 2022-10-20 17:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("football", "0011_alter_league_unique_together"),
        ("bets", "0013_auto_20221017_1102"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="odds",
            unique_together={("name", "fixture")},
        ),
    ]
