# Generated by Django 3.2.7 on 2022-11-17 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bets", "0014_alter_odds_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bet",
            name="odds",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bets",
                to="bets.odds",
                verbose_name="Odds",
            ),
        ),
    ]
