# Generated by Django 3.2.7 on 2024-03-19 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0033_auto_20240319_1422'),
        ('football', '0012_alter_league_kind_of_sport'),
        ('bets', '0015_alter_bet_odds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bets', to='user.client', verbose_name='Клієнт'),
        ),
        migrations.AlterField(
            model_name='bet',
            name='commands',
            field=models.CharField(default='', max_length=1000, verbose_name='Команди'),
        ),
        migrations.AlterField(
            model_name='bet',
            name='commision',
            field=models.FloatField(blank=True, null=True, verbose_name='Комісія (сума)'),
        ),
        migrations.AlterField(
            model_name='bet',
            name='country',
            field=models.CharField(default='', max_length=1000, verbose_name='Країна'),
        ),
        migrations.AlterField(
            model_name='bet',
            name='created_at',
            field=models.CharField(default='', max_length=1000, verbose_name='Час та дата створення ставки'),
        ),
        migrations.AlterField(
            model_name='bet',
            name='date_of_game',
            field=models.CharField(default='', max_length=1000, verbose_name='Час та дата матчу'),
        ),
        migrations.AlterField(
            model_name='bet',
            name='event',
            field=models.CharField(default='', max_length=1000, verbose_name='Тип ставки (точний рахунок, результат тощо)'),
        ),
        migrations.AlterField(
            model_name='bet',
            name='game_score',
            field=models.CharField(default='', max_length=1000, verbose_name='Рахунок гри'),
        ),
        migrations.AlterField(
            model_name='bet',
            name='league',
            field=models.CharField(default='', max_length=1000, verbose_name='Ліга'),
        ),
        migrations.AlterField(
            model_name='bet',
            name='odds_value',
            field=models.FloatField(default=0, verbose_name='КЕФ'),
        ),
        migrations.AlterField(
            model_name='bet',
            name='on',
            field=models.CharField(max_length=50, verbose_name='На який рахунок ставили'),
        ),
        migrations.AlterField(
            model_name='bet',
            name='result',
            field=models.FloatField(blank=True, null=True, verbose_name='Виграш'),
        ),
        migrations.AlterField(
            model_name='bet',
            name='stake',
            field=models.FloatField(verbose_name='Сума ставки'),
        ),
        migrations.AlterField(
            model_name='odds',
            name='fixture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='odds', to='football.match', verbose_name='Подія'),
        ),
        migrations.AlterField(
            model_name='odds',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='odds',
            name='name_en_us',
            field=models.CharField(max_length=255, null=True, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='odds',
            name='name_es',
            field=models.CharField(max_length=255, null=True, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='odds',
            name='name_fr',
            field=models.CharField(max_length=255, null=True, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='oddsdetail',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='oddsdetail',
            name='name_en_us',
            field=models.CharField(max_length=255, null=True, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='oddsdetail',
            name='name_es',
            field=models.CharField(max_length=255, null=True, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='oddsdetail',
            name='name_fr',
            field=models.CharField(max_length=255, null=True, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='oddsdetail',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100, verbose_name='Значення'),
        ),
    ]
