# Generated by Django 3.2.7 on 2024-11-01 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0038_payment_pricingplan'),
        ('bets', '0016_auto_20240319_1422'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opened', models.DateTimeField(blank=True, null=True)),
                ('closed', models.DateTimeField(blank=True, null=True)),
                ('traiding_pair', models.CharField(max_length=255)),
                ('tp_sl', models.CharField(max_length=255)),
                ('deposit', models.CharField(max_length=255)),
                ('closing_pnl', models.CharField(max_length=255)),
                ('exchange', models.CharField(max_length=255)),
                ('direction', models.CharField(max_length=255)),
                ('orders_type', models.CharField(max_length=255)),
                ('fee', models.CharField(max_length=255)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='user.client', verbose_name='Клієнт')),
            ],
        ),
    ]
