# Generated by Django 3.2.7 on 2024-11-29 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0017_trade'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='closing_fee',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='opening_fee',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='closing_pnl',
            field=models.CharField(max_length=255, verbose_name='Closed P&L (USDT)'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='fee',
            field=models.CharField(max_length=255, verbose_name='Commission'),
        ),
    ]
