# Generated by Django 3.2.7 on 2022-06-03 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("geo", "0001_initial"),
        ("bets", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="League",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50, verbose_name="League name")),
                (
                    "logo",
                    models.URLField(blank=True, null=True, verbose_name="League logo"),
                ),
                (
                    "flag",
                    models.URLField(blank=True, null=True, verbose_name="League flag"),
                ),
                (
                    "season",
                    models.PositiveSmallIntegerField(verbose_name="League season"),
                ),
                ("round", models.CharField(max_length=50, verbose_name="League round")),
                (
                    "country",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="geo.country",
                        verbose_name="League country",
                    ),
                ),
            ],
            options={
                "verbose_name": "League",
                "verbose_name_plural": "Leagues",
                "unique_together": {("title", "country")},
            },
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Team name")),
                (
                    "logo",
                    models.URLField(blank=True, null=True, verbose_name="Team logo"),
                ),
            ],
            options={
                "verbose_name": "Team",
                "verbose_name_plural": "Teams",
            },
        ),
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "event_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="bets.event",
                    ),
                ),
                (
                    "referee",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Match referee",
                    ),
                ),
                ("date", models.DateTimeField(verbose_name="Match date and time")),
                (
                    "away_team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="away_matches",
                        to="football.team",
                        verbose_name="Away team",
                    ),
                ),
                (
                    "home_team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="home_matches",
                        to="football.team",
                        verbose_name="Home team",
                    ),
                ),
                (
                    "league",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches",
                        to="football.league",
                        verbose_name="Match league",
                    ),
                ),
                (
                    "winer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="won_matches",
                        to="football.team",
                        verbose_name="Match winer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Match",
                "verbose_name_plural": "Matches",
            },
            bases=("bets.event",),
        ),
    ]
