# Generated by Django 3.2.7 on 2022-10-11 08:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("football", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="league",
            name="round_en_us",
            field=models.CharField(
                max_length=50, null=True, verbose_name="League round"
            ),
        ),
        migrations.AddField(
            model_name="league",
            name="round_es",
            field=models.CharField(
                max_length=50, null=True, verbose_name="League round"
            ),
        ),
        migrations.AddField(
            model_name="league",
            name="round_fr",
            field=models.CharField(
                max_length=50, null=True, verbose_name="League round"
            ),
        ),
        migrations.AddField(
            model_name="league",
            name="season_en_us",
            field=models.PositiveSmallIntegerField(
                null=True, verbose_name="League season"
            ),
        ),
        migrations.AddField(
            model_name="league",
            name="season_es",
            field=models.PositiveSmallIntegerField(
                null=True, verbose_name="League season"
            ),
        ),
        migrations.AddField(
            model_name="league",
            name="season_fr",
            field=models.PositiveSmallIntegerField(
                null=True, verbose_name="League season"
            ),
        ),
        migrations.AddField(
            model_name="league",
            name="title_en_us",
            field=models.CharField(
                max_length=50, null=True, verbose_name="League name"
            ),
        ),
        migrations.AddField(
            model_name="league",
            name="title_es",
            field=models.CharField(
                max_length=50, null=True, verbose_name="League name"
            ),
        ),
        migrations.AddField(
            model_name="league",
            name="title_fr",
            field=models.CharField(
                max_length=50, null=True, verbose_name="League name"
            ),
        ),
    ]
