# Generated by Django 3.2.7 on 2022-10-11 08:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("football", "0002_auto_20221011_0855"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="referee_en_us",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Match referee"
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="referee_es",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Match referee"
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="referee_fr",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Match referee"
            ),
        ),
    ]
