# Generated by Django 3.2.7 on 2022-10-11 09:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("football", "0003_auto_20221011_0858"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="title_en_us",
            field=models.CharField(max_length=100, null=True, verbose_name="Team name"),
        ),
        migrations.AddField(
            model_name="team",
            name="title_es",
            field=models.CharField(max_length=100, null=True, verbose_name="Team name"),
        ),
        migrations.AddField(
            model_name="team",
            name="title_fr",
            field=models.CharField(max_length=100, null=True, verbose_name="Team name"),
        ),
    ]
