# Generated by Django 3.2.7 on 2022-10-11 09:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("football", "0004_auto_20221011_0900"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="league",
            name="season_en_us",
        ),
        migrations.RemoveField(
            model_name="league",
            name="season_es",
        ),
        migrations.RemoveField(
            model_name="league",
            name="season_fr",
        ),
    ]
