# Generated by Django 3.2.7 on 2022-10-12 15:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("football", "0005_auto_20221011_0907"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="kind_of_sport",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "football"),
                    (2, "baseball"),
                    (3, "basketball"),
                    (4, "formula 1"),
                    (5, "handball"),
                    (6, "hockey"),
                    (7, "rugby"),
                    (8, "volleyball"),
                ],
                default=1,
                verbose_name="Вид спорта",
            ),
        ),
    ]
