# Generated by Django 3.2.7 on 2022-10-14 09:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("geo", "0002_auto_20221011_0902"),
        ("football", "0006_match_kind_of_sport"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="match",
            name="kind_of_sport",
        ),
        migrations.AddField(
            model_name="league",
            name="api_id",
            field=models.PositiveIntegerField(
                null=True, unique=True, verbose_name="Rapid api id"
            ),
        ),
        migrations.AddField(
            model_name="league",
            name="kind_of_sport",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "football"),
                    (2, "baseball"),
                    (3, "basketball"),
                    (4, "formula 1"),
                    (5, "handball"),
                    (6, "hockey"),
                    (7, "rugby"),
                    (8, "volleyball"),
                ],
                default=1,
                verbose_name="Вид спорта",
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="api_id",
            field=models.PositiveIntegerField(
                null=True, unique=True, verbose_name="Rapid api id"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="league",
            unique_together={("title", "country"), ("id", "api_id")},
        ),
    ]
