# Generated by Django 3.2.7 on 2022-10-14 12:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("football", "0007_auto_20221014_0928"),
    ]

    operations = [
        migrations.AlterField(
            model_name="league",
            name="season",
            field=models.CharField(max_length=250, verbose_name="League season"),
        ),
    ]
