# Generated by Django 3.2.7 on 2022-10-14 14:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("football", "0008_alter_league_season"),
    ]

    operations = [
        migrations.AlterField(
            model_name="league",
            name="api_id",
            field=models.PositiveIntegerField(null=True, verbose_name="Rapid api id"),
        ),
        migrations.AlterField(
            model_name="match",
            name="api_id",
            field=models.PositiveIntegerField(null=True, verbose_name="Rapid api id"),
        ),
    ]
