# Generated by Django 3.2.7 on 2022-10-14 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("football", "0009_auto_20221014_1420"),
    ]

    operations = [
        migrations.AlterField(
            model_name="match",
            name="away_team",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="away_matches",
                to="football.team",
                verbose_name="Away team",
            ),
        ),
    ]
