# Generated by Django 3.2.7 on 2022-10-20 13:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("football", "0010_alter_match_away_team"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="league",
            unique_together={("id", "api_id")},
        ),
    ]
