# Generated by Django 3.2.7 on 2024-03-19 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0011_alter_league_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='kind_of_sport',
            field=models.PositiveSmallIntegerField(choices=[(1, 'football'), (2, 'baseball'), (3, 'basketball'), (4, 'formula 1'), (5, 'handball'), (6, 'hockey'), (7, 'rugby'), (8, 'volleyball')], default=1, verbose_name='Вид спорту'),
        ),
    ]
