# Generated by Django 3.2.7 on 2024-05-28 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0034_satellite_is_original'),
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historylog',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='user.client'),
        ),
        migrations.AddField(
            model_name='historylog',
            name='salesman',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='user.salesman'),
        ),
    ]
