# Generated by Django 3.2.7 on 2024-05-29 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0002_auto_20240528_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historylog',
            name='action_time',
            field=models.DateTimeField(),
        ),
    ]
