# Generated by Django 3.2.7 on 2024-06-21 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0004_auto_20240610_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='historylog',
            name='additional_info',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='historylog',
            name='client',
            field=models.CharField(default='None', max_length=255),
        ),
    ]
