# Generated by Django 3.2.7 on 2022-10-11 09:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("geo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="country",
            name="title_en_us",
            field=models.CharField(
                max_length=50, null=True, unique=True, verbose_name="Country"
            ),
        ),
        migrations.AddField(
            model_name="country",
            name="title_es",
            field=models.CharField(
                max_length=50, null=True, unique=True, verbose_name="Country"
            ),
        ),
        migrations.AddField(
            model_name="country",
            name="title_fr",
            field=models.CharField(
                max_length=50, null=True, unique=True, verbose_name="Country"
            ),
        ),
    ]
