# Generated by Django 3.2.7 on 2022-06-03 15:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Create date"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Active user"),
                ),
                (
                    "is_staff",
                    models.BooleanField(default=False, verbose_name="Staff status"),
                ),
                (
                    "password",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Password"
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        max_length=25, null=True, unique=True, verbose_name="Username"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Surname"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=255, null=True, verbose_name="Email"
                    ),
                ),
                (
                    "invitation_code",
                    models.CharField(max_length=20, verbose_name="Invitation code"),
                ),
                ("is_satellite", models.BooleanField(default=False)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.Group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.Permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
            },
        ),
        migrations.CreateModel(
            name="Salesman",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
            ],
            options={
                "verbose_name": "Salesman",
                "verbose_name_plural": "Salesmans",
            },
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "user_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="user.user",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=300, verbose_name="Full name"),
                ),
                (
                    "password_visible",
                    models.CharField(
                        editable=False,
                        max_length=255,
                        null=True,
                        verbose_name="Password visible",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Create date",
                    ),
                ),
                (
                    "salesman",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clients",
                        to="user.salesman",
                        verbose_name="Salesman",
                    ),
                ),
            ],
            options={
                "verbose_name": "Client",
                "verbose_name_plural": "Clients",
            },
            bases=("user.user",),
        ),
        migrations.CreateModel(
            name="Satellite",
            fields=[
                (
                    "user_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="user.user",
                    ),
                ),
                ("uuid", models.CharField(editable=False, max_length=15)),
                (
                    "block_balance",
                    models.PositiveIntegerField(verbose_name="Block balance"),
                ),
                (
                    "active_balance",
                    models.PositiveIntegerField(verbose_name="Active balance"),
                ),
                ("withdrawal", models.PositiveIntegerField(verbose_name="Withdrawal")),
                (
                    "interval",
                    models.DurationField(
                        blank=True, null=True, verbose_name="Interval"
                    ),
                ),
                (
                    "allow_auth",
                    models.BooleanField(
                        default=True,
                        help_text="Allow client to login in this satellite",
                        verbose_name="Allow login",
                    ),
                ),
                ("system", models.BooleanField(default=False)),
                (
                    "password_visible",
                    models.CharField(
                        editable=False,
                        max_length=255,
                        null=True,
                        verbose_name="Password visible",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Create date",
                    ),
                ),
                (
                    "satellite_client",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="satellites",
                        to="user.client",
                        verbose_name="Client",
                    ),
                ),
            ],
            options={
                "verbose_name": "Satellite",
                "verbose_name_plural": "Satellites",
            },
            bases=("user.user",),
        ),
    ]
