# Generated by Django 3.2.7 on 2022-06-03 16:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_satellite",
        ),
        migrations.AlterField(
            model_name="satellite",
            name="uuid",
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
