# Generated by Django 3.2.7 on 2022-06-06 13:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_auto_20220603_1626"),
    ]

    operations = [
        migrations.AddField(
            model_name="satellite",
            name="blocked",
            field=models.BooleanField(default=True, verbose_name="Blocked"),
        ),
        migrations.AddField(
            model_name="satellite",
            name="order",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="Order"
            ),
        ),
    ]
