# Generated by Django 3.2.7 on 2022-06-04 12:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_auto_20220603_1626"),
    ]

    operations = [
        migrations.AddField(
            model_name="satellite",
            name="migration_time",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="Migration date",
            ),
        ),
    ]
