# Generated by Django 3.2.7 on 2022-06-06 14:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0003_auto_20220606_1342"),
    ]

    operations = [
        migrations.AddField(
            model_name="satellite",
            name="message_for_blocked",
            field=models.TextField(
                default="Your account has been blocked. Please contact technical support",
                verbose_name="Message for blocked",
            ),
        ),
    ]
