# Generated by Django 3.2.7 on 2022-06-08 08:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0003_satellite_migration_time"),
        ("user", "0004_satellite_message_for_blocked"),
    ]

    operations = []
