# Generated by Django 3.2.7 on 2022-06-13 10:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0005_merge_20220608_0842"),
    ]

    operations = [
        migrations.AlterField(
            model_name="satellite",
            name="uuid",
            field=models.CharField(max_length=15),
        ),
    ]
