# Generated by Django 3.2.7 on 2022-06-13 12:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0006_alter_satellite_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                max_length=100, null=True, unique=True, verbose_name="Username"
            ),
        ),
    ]
