# Generated by Django 3.2.7 on 2022-06-13 11:49
from django import forms, utils
from django.db import migrations


def forwards_func(apps, schema_editor):
    Client = apps.get_model("user", "client")
    Satellite = apps.get_model("user", "satellite")

    clients = Client.objects.all()
    system_satellites = (
        Satellite.objects.filter(system=True)
        .filter(satellite_client__isnull=True)
        .all()
    )

    for client in clients:
        for satellite in system_satellites:
            satellite_data = {
                **forms.model_to_dict(
                    satellite,
                    exclude=[
                        "id",
                        "satellite_client",
                        "user_ptr",
                        "groups",
                        "user_permissions",
                    ],
                ),
                "username": f"{satellite.username}_{utils.timezone.now().timestamp()}",
                "satellite_client": client,
            }
            Satellite.objects.create(**satellite_data)


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0008_alter_user_username"),
    ]

    operations = [
        migrations.RunPython(
            forwards_func,
        )
    ]
