# Generated by Django 3.2.7 on 2022-10-11 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0009_auto_20220613_1208"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="client",
            options={"verbose_name": "Клиент", "verbose_name_plural": "Клиенты"},
        ),
        migrations.AlterModelOptions(
            name="salesman",
            options={"verbose_name": "Продавец", "verbose_name_plural": "Продавцы"},
        ),
        migrations.AlterModelOptions(
            name="satellite",
            options={
                "verbose_name": "Сателлит",
                "verbose_name_plural": "Все сателлиты",
            },
        ),
        migrations.AlterField(
            model_name="client",
            name="full_name",
            field=models.CharField(max_length=300, verbose_name="ФИ (для себя)"),
        ),
        migrations.AlterField(
            model_name="client",
            name="password_visible",
            field=models.CharField(
                editable=False,
                max_length=255,
                null=True,
                verbose_name="Пароль от чистилища",
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="salesman",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="clients",
                to="user.salesman",
                verbose_name="Продавец",
            ),
        ),
        migrations.AlterField(
            model_name="satellite",
            name="active_balance",
            field=models.PositiveIntegerField(verbose_name="Актив баланс"),
        ),
        migrations.AlterField(
            model_name="satellite",
            name="allow_auth",
            field=models.BooleanField(
                default=True, verbose_name="Разрешить логин в ЛК"
            ),
        ),
        migrations.AlterField(
            model_name="satellite",
            name="block_balance",
            field=models.PositiveIntegerField(verbose_name="Заблок баланс"),
        ),
        migrations.AlterField(
            model_name="satellite",
            name="blocked",
            field=models.BooleanField(default=True, verbose_name="Заблокировать"),
        ),
        migrations.AlterField(
            model_name="satellite",
            name="interval",
            field=models.DurationField(blank=True, null=True, verbose_name="Интервал"),
        ),
        migrations.AlterField(
            model_name="satellite",
            name="message_for_blocked",
            field=models.TextField(
                default="Your account has been blocked. Please contact technical support",
                verbose_name="Сообщение для заблокированного",
            ),
        ),
        migrations.AlterField(
            model_name="satellite",
            name="order",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="Номер в списке"
            ),
        ),
        migrations.AlterField(
            model_name="satellite",
            name="withdrawal",
            field=models.PositiveIntegerField(verbose_name="Вывод"),
        ),
    ]
