# Generated by Django 3.2.7 on 2022-12-05 20:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0010_auto_20221011_0845"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="ip",
            field=models.TextField(null=True, verbose_name="IP"),
        ),
    ]
