# Generated by Django 3.2.7 on 2022-12-08 08:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0011_user_ip"),
    ]

    operations = [
        migrations.CreateModel(
            name="Entrance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "time",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Time"
                    ),
                ),
                (
                    "ip",
                    models.CharField(
                        blank=True, max_length=40, null=True, verbose_name="IP"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="entrances",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Entrance",
                "verbose_name_plural": "Entrances",
                "ordering": ["-time"],
            },
        ),
    ]
