# Generated by Django 3.2.7 on 2022-12-08 08:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0012_entrance"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="entrance",
            options={
                "ordering": ["-time"],
                "verbose_name": "История входа",
                "verbose_name_plural": "История входов",
            },
        ),
    ]
