# Generated by Django 3.2.7 on 2022-12-08 10:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0013_alter_entrance_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="entrance",
            name="user_order",
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="ID"),
        ),
    ]
