# Generated by Django 3.2.7 on 2023-05-08 08:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("geo", "0002_auto_20221011_0902"),
        ("user", "0014_entrance_user_order"),
    ]

    operations = [
        migrations.CreateModel(
            name="Requisites",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=16, verbose_name="Title")),
                ("show", models.BooleanField(default=True, verbose_name="Hide")),
                (
                    "icon",
                    models.PositiveSmallIntegerField(choices=[], verbose_name="Icon"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="address",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Address"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="allow_password_update",
            field=models.BooleanField(
                default=True, verbose_name="Allow password update"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="born",
            field=models.DateField(blank=True, null=True, verbose_name="Born date"),
        ),
        migrations.AddField(
            model_name="user",
            name="city",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="City"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="country",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="geo.country",
                verbose_name="Country",
            ),
        ),
        migrations.CreateModel(
            name="UserPasswords",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=255)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="passwords",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
