# Generated by Django 3.2.7 on 2023-05-08 09:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0015_auto_20230508_0846"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserPasswords",
        ),
    ]
