# Generated by Django 3.2.7 on 2023-05-08 15:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0017_clientpasswords_satellitepasswords"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="country",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Country"
            ),
        ),
    ]
