# Generated by Django 3.2.7 on 2023-05-08 16:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0018_alter_user_country"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="clientpasswords",
            options={
                "verbose_name": "Пароль клиента",
                "verbose_name_plural": "Пароли клиента",
            },
        ),
        migrations.AlterModelOptions(
            name="requisites",
            options={"verbose_name": "Реквизит", "verbose_name_plural": "Реквизиты"},
        ),
        migrations.AlterModelOptions(
            name="satellitepasswords",
            options={
                "verbose_name": "Пароль сателита",
                "verbose_name_plural": "Пароли сателита",
            },
        ),
    ]
