# Generated by Django 3.2.7 on 2023-05-20 14:01

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0019_auto_20230508_1628"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                max_length=128,
                null=True,
                region=None,
                unique=True,
                verbose_name="Phone",
            ),
        ),
    ]
