# Generated by Django 3.2.7 on 2023-05-20 18:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0021_alter_requisites_icon"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="clientpasswords",
            name="password",
        ),
        migrations.RemoveField(
            model_name="satellitepasswords",
            name="password",
        ),
        migrations.AddField(
            model_name="clientpasswords",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Дата изменения пароля"
            ),
        ),
        migrations.AddField(
            model_name="clientpasswords",
            name="new_password",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="clientpasswords",
            name="old_password",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="satellitepasswords",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Дата изменения пароля"
            ),
        ),
        migrations.AddField(
            model_name="satellitepasswords",
            name="new_password",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="satellitepasswords",
            name="old_password",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
