# Generated by Django 3.2.7 on 2023-05-20 20:20

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0022_auto_20230520_1849"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientpasswords",
            name="new_password",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Новый пароль"
            ),
        ),
        migrations.AlterField(
            model_name="clientpasswords",
            name="old_password",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Старый пароль"
            ),
        ),
        migrations.AlterField(
            model_name="requisites",
            name="icon",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "Visa"),
                    (2, "Mastercard"),
                    (3, "Maestro"),
                    (4, "Skrill"),
                    (5, "GooglePay"),
                    (6, "Payeer"),
                    (7, "PayPal"),
                    (8, "Advcash"),
                    (9, "Netteller"),
                    (10, "Swift"),
                ],
                verbose_name="Иконка",
            ),
        ),
        migrations.AlterField(
            model_name="requisites",
            name="show",
            field=models.BooleanField(default=True, verbose_name="Затемнять"),
        ),
        migrations.AlterField(
            model_name="requisites",
            name="title",
            field=models.CharField(max_length=16, verbose_name="Номер карты"),
        ),
        migrations.AlterField(
            model_name="satellitepasswords",
            name="new_password",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Новый пароль"
            ),
        ),
        migrations.AlterField(
            model_name="satellitepasswords",
            name="old_password",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Старый пароль"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="address",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Адрес"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="allow_password_update",
            field=models.BooleanField(default=True, verbose_name="Можно менять пароль"),
        ),
        migrations.AlterField(
            model_name="user",
            name="born",
            field=models.DateField(blank=True, null=True, verbose_name="Дата рождения"),
        ),
        migrations.AlterField(
            model_name="user",
            name="city",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Город"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="country",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Страна"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                blank=True, max_length=255, null=True, verbose_name="Почта"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Фамилия"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Имя"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                max_length=128,
                null=True,
                region=None,
                unique=True,
                verbose_name="Номер телефона",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                max_length=100, null=True, unique=True, verbose_name="Ник"
            ),
        ),
    ]
