# Generated by Django 3.2.7 on 2023-06-14 19:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0023_auto_20230520_2020"),
    ]

    operations = [
        migrations.AddField(
            model_name="requisites",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="requisites",
                to="user.client",
                verbose_name="Client",
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="password_visible",
            field=models.CharField(
                editable=False,
                max_length=255,
                null=True,
                validators=[
                    django.core.validators.MinLengthValidator(8),
                    django.core.validators.RegexValidator(
                        message="Password must be between 8 and 20 characters, contain at least one uppercase letter, one digit, and only Latin characters.",
                        regex="^(?=.*[A-Z])(?=.*\\d)[A-Za-z\\d]{8,20}$",
                    ),
                ],
                verbose_name="Пароль от чистилища",
            ),
        ),
        migrations.AlterField(
            model_name="satellite",
            name="password_visible",
            field=models.CharField(
                editable=False,
                max_length=255,
                null=True,
                validators=[
                    django.core.validators.MinLengthValidator(8),
                    django.core.validators.RegexValidator(
                        message="Password must be between 8 and 20 characters, contain at least one uppercase letter, one digit, and only Latin characters.",
                        regex="^(?=.*[A-Z])(?=.*\\d)[A-Za-z\\d]{8,20}$",
                    ),
                ],
                verbose_name="Password visible",
            ),
        ),
    ]
