# Generated by Django 3.2.7 on 2023-06-14 22:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0024_auto_20230614_1946"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(
                max_length=255,
                null=True,
                validators=[
                    django.core.validators.MinLengthValidator(8),
                    django.core.validators.RegexValidator(
                        message="Password must be between 8 and 20 characters, contain at least one uppercase letter, one digit, and only Latin characters.",
                        regex="^(?=.*[A-Z])(?=.*\\d)[A-Za-z\\d]{8,20}$",
                    ),
                ],
                verbose_name="Password",
            ),
        ),
    ]
