# Generated by Django 3.2.7 on 2023-06-14 22:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0025_alter_user_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="city",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Город"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="country",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Страна"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(
                blank=True,
                max_length=15,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="This field must contain only Latin characters and numbers.",
                        regex="^[a-zA-Z0-9]+$",
                    )
                ],
                verbose_name="Фамилия",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(
                blank=True, max_length=15, null=True, verbose_name="Имя"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                max_length=100,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="This field must contain only Latin characters and numbers.",
                        regex="^[a-zA-Z0-9]+$",
                    )
                ],
                verbose_name="Ник",
            ),
        ),
    ]
