# Generated by Django 3.2.7 on 2023-06-15 15:41

import django.core.validators
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0026_auto_20230614_2241"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="password_visible",
            field=models.CharField(
                max_length=255,
                null=True,
                validators=[
                    django.core.validators.MinLengthValidator(8),
                    django.core.validators.RegexValidator(
                        message="Password must be between 8 and 20 characters, contain at least one uppercase letter, one digit, and only Latin characters.",
                        regex="^(?=.*[A-Z])(?=.*\\d)[A-Za-z\\d]{8,20}$",
                    ),
                ],
                verbose_name="Пароль от чистилища",
            ),
        ),
        migrations.AlterField(
            model_name="satellite",
            name="password_visible",
            field=models.CharField(
                max_length=255,
                null=True,
                validators=[
                    django.core.validators.MinLengthValidator(8),
                    django.core.validators.RegexValidator(
                        message="Password must be between 8 and 20 characters, contain at least one uppercase letter, one digit, and only Latin characters.",
                        regex="^(?=.*[A-Z])(?=.*\\d)[A-Za-z\\d]{8,20}$",
                    ),
                ],
                verbose_name="Password visible",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                max_length=128,
                null=True,
                region=None,
                verbose_name="Номер телефона",
            ),
        ),
    ]
