# Generated by Django 3.2.7 on 2023-06-16 12:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0027_auto_20230615_1541"),
    ]

    operations = [
        migrations.AlterField(
            model_name="requisites",
            name="title",
            field=models.CharField(max_length=1500, verbose_name="Номер карты"),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(
                blank=True,
                max_length=15,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="This field must contain only Latin characters and numbers.",
                        regex="^[a-zA-z0-9\\-\\_]+$",
                    )
                ],
                verbose_name="Фамилия",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                max_length=100,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="This field must contain only Latin characters and numbers.",
                        regex="^[a-zA-z0-9\\-\\_]+$",
                    )
                ],
                verbose_name="Ник",
            ),
        ),
    ]
