# Generated by Django 3.2.7 on 2023-06-16 12:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0028_auto_20230616_1242"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="password_visible",
            field=models.CharField(
                max_length=255,
                null=True,
                validators=[
                    django.core.validators.MinLengthValidator(8),
                    django.core.validators.RegexValidator(
                        message="Password must be between 8 and 20 characters, contain at least one uppercase letter, one digit, and only Latin characters.",
                        regex="^(?=.*[A-Z])(?=.*\\d)[A-Za-z\\d]{8,30}$",
                    ),
                ],
                verbose_name="Пароль от чистилища",
            ),
        ),
        migrations.AlterField(
            model_name="satellite",
            name="password_visible",
            field=models.CharField(
                max_length=255,
                null=True,
                validators=[
                    django.core.validators.MinLengthValidator(8),
                    django.core.validators.RegexValidator(
                        message="Password must be between 8 and 20 characters, contain at least one uppercase letter, one digit, and only Latin characters.",
                        regex="^(?=.*[A-Z])(?=.*\\d)[A-Za-z\\d]{8,30}$",
                    ),
                ],
                verbose_name="Password visible",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(
                max_length=255,
                null=True,
                validators=[
                    django.core.validators.MinLengthValidator(8),
                    django.core.validators.RegexValidator(
                        message="Password must be between 8 and 20 characters, contain at least one uppercase letter, one digit, and only Latin characters.",
                        regex="^(?=.*[A-Z])(?=.*\\d)[A-Za-z\\d]{8,30}$",
                    ),
                ],
                verbose_name="Password",
            ),
        ),
    ]
