# Generated by Django 3.2.7 on 2023-06-16 17:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0029_auto_20230616_1248"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                blank=True, max_length=15, null=True, verbose_name="Номер телефона"
            ),
        ),
    ]
