# Generated by Django 3.2.7 on 2023-06-19 09:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0030_alter_user_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="requisites",
            name="icon",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "Visa"),
                    (2, "Mastercard"),
                    (3, "Maestro"),
                    (4, "Skrill"),
                    (5, "GooglePay"),
                    (6, "Payeer"),
                    (7, "PayPal"),
                    (8, "Advcash"),
                    (9, "Netteller"),
                    (10, "Swift"),
                    (11, "МИР"),
                ],
                verbose_name="Иконка",
            ),
        ),
    ]
