# Generated by Django 3.2.7 on 2023-09-18 07:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0031_alter_requisites_icon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Номер телефона"
            ),
        ),
    ]
