# Generated by Django 3.2.7 on 2024-03-19 12:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0032_auto_20230918_1054'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Клієнт', 'verbose_name_plural': 'Клієнти'},
        ),
        migrations.AlterModelOptions(
            name='clientpasswords',
            options={'verbose_name': 'Пароль клієнта', 'verbose_name_plural': 'Паролі клієнта'},
        ),
        migrations.AlterModelOptions(
            name='entrance',
            options={'ordering': ['-time'], 'verbose_name': 'Історія входу', 'verbose_name_plural': 'Історія входів'},
        ),
        migrations.AlterModelOptions(
            name='requisites',
            options={'verbose_name': 'Реквізит', 'verbose_name_plural': 'Реквізити'},
        ),
        migrations.AlterModelOptions(
            name='salesman',
            options={'verbose_name': 'Продавець', 'verbose_name_plural': 'Продавці'},
        ),
        migrations.AlterModelOptions(
            name='satellite',
            options={'verbose_name': 'Сателіт', 'verbose_name_plural': 'Усі сателіти'},
        ),
        migrations.AlterModelOptions(
            name='satellitepasswords',
            options={'verbose_name': 'Пароль сателіту', 'verbose_name_plural': 'Паролі сателіту'},
        ),
        migrations.AlterField(
            model_name='client',
            name='full_name',
            field=models.CharField(max_length=300, verbose_name='ПІ (для себе)'),
        ),
        migrations.AlterField(
            model_name='client',
            name='password_visible',
            field=models.CharField(max_length=255, null=True, validators=[django.core.validators.MinLengthValidator(8), django.core.validators.RegexValidator(message='Password must be between 8 and 30 characters, contain at least one uppercase letter, one digit, and only Latin characters.', regex='(?=.*[A-Z])(?=.*\\d)[A-Za-z\\d_-]{8,30}$')], verbose_name='Пароль від чистилища'),
        ),
        migrations.AlterField(
            model_name='client',
            name='salesman',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='user.salesman', verbose_name='Продавець'),
        ),
        migrations.AlterField(
            model_name='clientpasswords',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата зміни паролю'),
        ),
        migrations.AlterField(
            model_name='clientpasswords',
            name='new_password',
            field=models.CharField(max_length=255, null=True, verbose_name='Новий пароль'),
        ),
        migrations.AlterField(
            model_name='clientpasswords',
            name='old_password',
            field=models.CharField(max_length=255, null=True, verbose_name='Старий пароль'),
        ),
        migrations.AlterField(
            model_name='requisites',
            name='icon',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Visa'), (2, 'Mastercard'), (3, 'Maestro'), (4, 'Skrill'), (5, 'GooglePay'), (6, 'Payeer'), (7, 'PayPal'), (8, 'Advcash'), (9, 'Netteller'), (10, 'Swift'), (11, 'МИР')], verbose_name='Іконка'),
        ),
        migrations.AlterField(
            model_name='requisites',
            name='show',
            field=models.BooleanField(default=True, verbose_name='Затемнювати'),
        ),
        migrations.AlterField(
            model_name='requisites',
            name='title',
            field=models.CharField(max_length=1500, verbose_name='Номер картки'),
        ),
        migrations.AlterField(
            model_name='satellite',
            name='allow_auth',
            field=models.BooleanField(default=True, verbose_name='Дозволити логін в ОК'),
        ),
        migrations.AlterField(
            model_name='satellite',
            name='blocked',
            field=models.BooleanField(default=True, verbose_name='Заблокувати'),
        ),
        migrations.AlterField(
            model_name='satellite',
            name='interval',
            field=models.DurationField(blank=True, null=True, verbose_name='Інтервал'),
        ),
        migrations.AlterField(
            model_name='satellite',
            name='message_for_blocked',
            field=models.TextField(default='Your account has been blocked. Please contact technical support', verbose_name='Повідомлення для заблокованого'),
        ),
        migrations.AlterField(
            model_name='satellite',
            name='order',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Номер у списку'),
        ),
        migrations.AlterField(
            model_name='satellite',
            name='password_visible',
            field=models.CharField(max_length=255, null=True, validators=[django.core.validators.MinLengthValidator(8), django.core.validators.RegexValidator(message='Password must be between 8 and 30 characters, contain at least one uppercase letter, one digit, and only Latin characters.', regex='(?=.*[A-Z])(?=.*\\d)[A-Za-z\\d_-]{8,30}$')], verbose_name='Password visible'),
        ),
        migrations.AlterField(
            model_name='satellite',
            name='withdrawal',
            field=models.PositiveIntegerField(verbose_name='Виведення'),
        ),
        migrations.AlterField(
            model_name='satellitepasswords',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата зміни паролю'),
        ),
        migrations.AlterField(
            model_name='satellitepasswords',
            name='new_password',
            field=models.CharField(max_length=255, null=True, verbose_name='Новий пароль'),
        ),
        migrations.AlterField(
            model_name='satellitepasswords',
            name='old_password',
            field=models.CharField(max_length=255, null=True, verbose_name='Старий пароль'),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Адреса'),
        ),
        migrations.AlterField(
            model_name='user',
            name='allow_password_update',
            field=models.BooleanField(default=True, verbose_name='Можна міняти пароль'),
        ),
        migrations.AlterField(
            model_name='user',
            name='born',
            field=models.DateField(blank=True, null=True, verbose_name='Дата народження'),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Місто'),
        ),
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Країна'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='Пошта'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='This field must contain only Latin characters and numbers.', regex='^[a-zA-z0-9\\-\\_]+$')], verbose_name='Прізвище'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name="Ім'я"),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=255, null=True, validators=[django.core.validators.MinLengthValidator(8), django.core.validators.RegexValidator(message='Password must be between 8 and 30 characters, contain at least one uppercase letter, one digit, and only Latin characters.', regex='(?=.*[A-Z])(?=.*\\d)[A-Za-z\\d_-]{8,30}$')], verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефону'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=100, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='This field must contain only Latin characters and numbers.', regex='^[a-zA-z0-9\\-\\_]+$')], verbose_name='Нік'),
        ),
    ]
