# Generated by Django 3.2.7 on 2024-03-19 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0033_auto_20240319_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='satellite',
            name='is_original',
            field=models.BooleanField(default=False),
        ),
    ]
