# Generated by Django 3.2.7 on 2024-10-14 11:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0034_satellite_is_original'),
    ]

    operations = [
        migrations.AddField(
            model_name='satellite',
            name='second_interval',
            field=models.DurationField(blank=True, null=True, verbose_name='Інтервал актив-виведення'),
        ),
        migrations.AddField(
            model_name='satellite',
            name='second_migration_time',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Migration date (withdrawal)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='satellite',
            name='interval',
            field=models.DurationField(blank=True, null=True, verbose_name='Інтервал блок-актив'),
        ),
        migrations.AlterField(
            model_name='satellite',
            name='migration_time',
            field=models.DateTimeField(editable=False, verbose_name='Migration date (unblock)'),
        ),
    ]
