# Generated by Django 3.2.7 on 2024-10-16 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0035_auto_20241014_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='satellite',
            name='migration_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Migration date (unblock)'),
        ),
        migrations.AlterField(
            model_name='satellite',
            name='second_migration_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Migration date (withdrawal)'),
        ),
    ]
