# Generated by Django 3.2.7 on 2024-10-22 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0036_auto_20241016_1012'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('account_number', models.CharField(max_length=6)),
                ('subject', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
    ]
