# Generated by Django 3.2.7 on 2024-11-07 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0038_payment_pricingplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='total_balance',
            field=models.BigIntegerField(default=0, verbose_name='Total balance'),
        ),
    ]
