# Generated by Django 3.2.7 on 2024-11-28 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0039_client_total_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='satellite',
            name='uuid',
            field=models.CharField(max_length=50),
        ),
    ]
