# Generated by Django 3.2.7 on 2024-11-28 08:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0040_alter_satellite_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator(message='This field must contain only Latin characters and numbers.', regex='^[a-zA-z0-9\\-\\_]+$')], verbose_name='Прізвище'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="Ім'я"),
        ),
    ]
