# Generated by Django 3.2.7 on 2025-01-10 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0041_auto_20241128_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='commission',
            field=models.FloatField(default=0.025, verbose_name='Комісія біржі'),
        ),
        migrations.AddField(
            model_name='client',
            name='growth_rate',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Відсоток росту'),
        ),
        migrations.AddField(
            model_name='client',
            name='shoulder',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Плече'),
        ),
        migrations.AddField(
            model_name='satellite',
            name='deposit',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Депозит'),
        ),
        migrations.AlterField(
            model_name='client',
            name='total_balance',
            field=models.FloatField(default=0, verbose_name='Total balance'),
        ),
        migrations.AlterField(
            model_name='satellite',
            name='active_balance',
            field=models.FloatField(verbose_name='Актив баланс'),
        ),
        migrations.AlterField(
            model_name='satellite',
            name='block_balance',
            field=models.FloatField(verbose_name='Заблок баланс'),
        ),
        migrations.AlterField(
            model_name='satellite',
            name='withdrawal',
            field=models.FloatField(verbose_name='Виведення'),
        ),
    ]
