# Generated by Django 3.2.7 on 2025-02-28 14:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0042_auto_20250110_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='total_balance',
            field=models.BigIntegerField(default=0, verbose_name='Total balance'),
        ),
        migrations.AlterField(
            model_name='requisites',
            name='icon',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Visa'), (2, 'Mastercard'), (3, 'Maestro'), (4, 'Skrill'), (5, 'GooglePay'), (6, 'Payeer'), (7, 'PayPal'), (8, 'Advcash'), (9, 'Netteller'), (10, 'Swift'), (11, 'МИР'), (12, 'USDT(TRC20)')], verbose_name='Іконка'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Прізвище'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=100, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='This field must contain only Latin characters and numbers.', regex='^[a-zA-Z0-9\\-\\_\\s]+$')], verbose_name='Нік'),
        ),
    ]
