# Generated by Django 3.2.7 on 2025-03-05 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0043_auto_20250228_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='commission',
            field=models.FloatField(default=0.00025, verbose_name='Комісія біржі'),
        ),
    ]
