# Generated by Django 3.2.7 on 2025-03-05 22:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0044_alter_client_commission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=100, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='This field must contain only Latin characters and numbers.', regex='^[a-zA-Z0-9\\-\\_\\s]+$')], verbose_name='Логін'),
        ),
    ]
