# Generated by Django 3.2.7 on 2025-03-05 23:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0045_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(
                max_length=100,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message='This field must contain only Latin characters and numbers.',
                        regex='^[a-zA-Z0-9\\-\\_\\s]+$',
                    )
                ],
                verbose_name='Login',
            ),
        ),
    ]
