# Generated by Django 3.2.7 on 2025-03-07 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0046_alter_user_username_again'),
    ]

    operations = [
        migrations.AlterField(
            model_name='satellite',
            name='deposit',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Депозит'),
        ),
    ]
