# Generated by Django 3.2.7 on 2025-03-07 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0047_alter_satellite_deposit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='satellite',
            name='active_balance',
            field=models.IntegerField(verbose_name='Актив баланс'),
        ),
        migrations.AlterField(
            model_name='satellite',
            name='block_balance',
            field=models.IntegerField(verbose_name='Заблок баланс'),
        ),
        migrations.AlterField(
            model_name='satellite',
            name='withdrawal',
            field=models.IntegerField(verbose_name='Виведення'),
        ),
    ]
