# Generated by Django 3.2.7 on 2025-05-14 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0048_auto_20250307_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
