# Generated by Django 3.2.7 on 2025-05-14 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0049_client_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='document_verified',
            field=models.BooleanField(default=False),
        ),
    ]
