# Generated by Django 3.2.7 on 2025-06-16 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0050_client_document_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='document_verified',
        ),
        migrations.RemoveField(
            model_name='client',
            name='email_verified',
        ),
        migrations.AddField(
            model_name='user',
            name='document_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
