# Generated by Django 3.2.7 on 2025-08-19 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0051_auto_20250616_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='document_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]