# Generated by Django 3.2.7 on 2025-11-10 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0052_user_document_verified_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisites',
            name='icon',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Visa'), (2, 'Mastercard'), (3, 'Maestro'), (4, 'Skrill'), (5, 'GooglePay'), (6, 'Payeer'), (7, 'PayPal'), (8, 'Advcash'), (9, 'Netteller'), (10, 'Swift'), (11, 'МИР'), (12, 'USDT(TRC20)'), (13, 'USDT(BEP-20)')], verbose_name='Іконка'),
        ),
    ]
